version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "03:52"
    timezone: America/Chicago
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: activesupport
    versions:
    - 6.1.3
  - dependency-name: activemodel
    versions:
    - 6.1.2.1
