---
language: ruby
os: linux
dist: bionic
cache: bundler
rvm:
  - 2.7.0
notifications:
  email:
    on_success: never
    on_failure: always
script:
  - bin/rubocop $(git ls-tree -r HEAD --name-only) --force-exclusion --format clang
  - bin/rspec
