name: Run Tests, Linters, Etc.

on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Run RuboCop
      run: bin/rubocop --format clang
    - name: Run RSpec tests
      run: bin/rspec --format progress
    - name: Ensure no git diff
      run: git diff --exit-code && git diff-index --quiet --cached HEAD
    - name: Upload Code Coverage
      uses: codecov/codecov-action@v3
      with:
        directory: tmp/simple_cov
